#!/bin/bash
set -e

GIT_URI="git@github.com:parente/sandbox.wiki.git"
GIT_SANDBOX="sandbox.wiki"
GIT_SHA_TAG=${SOURCE_COMMIT:0:12}
MANIFEST_FILE="manifests/${DOCKER_REPO}}-${SOURCE_COMMIT:0:12}.md"

echo "INFO: configuring git agent"
eval $(ssh-agent -s)
ssh-add <(echo "$DEPLOY_KEY")
ssh-add -l
git config --global user.email "jupyter@googlegroups.com"
git config --global user.name "Jupyter Docker Stacks"

echo "INFO: cloning $GIT_URI"
git clone "$GIT_URI"
pushd "$GIT_SANDBOX"

echo "INFO: creating $MANIFEST_FILE"
mkdir -p manifests
source manifest.tmpl

echo "INFO: pushing to $GIT_URI"
git add .
git commit -m "DOC: Build ${MANIFEST_FILE}"
git push -u origin master

popd
ssh-agent -k

echo "INFO: done"