#!/bin/bash
set -e

echo "INFO: populating variables"
BUILD_TIMESTAMP=$(date -u +%FT%TZ)
WORKDIR=$(mktemp -d)
GIT_URI="git@github.com:parente/sandbox.wiki.git"
GIT_SANDBOX="${WORKDIR}/sandbox.wiki"
GIT_SHA_TAG=${SOURCE_COMMIT:0:12}
IMAGE_SHORT_NAME=$(basename $DOCKER_REPO)
MANIFEST_FILE="${GIT_SANDBOX}/manifests/${IMAGE_SHORT_NAME}-${SOURCE_COMMIT:0:12}.md"
INDEX_FILE="${GIT_SANDBOX}/Home.md"

echo "INFO: configuring git"
eval $(ssh-agent -s)
ssh-add <(echo "$DEPLOY_KEY")
ssh-add -l
git config --global user.email "jupyter@googlegroups.com"
git config --global user.name "Jupyter Docker Stacks"

echo "INFO: cloning $GIT_URI"
pushd "$WORKDIR"
git clone "$GIT_URI"
popd

echo "INFO: creating $MANIFEST_FILE"
mkdir -p $(dirname "$MANIFEST_FILE")
source hooks/manifest.tmpl
source hooks/index.tmpl

echo "INFO: pushing to $GIT_URI"
pushd "$GIT_SANDBOX"
git add .
git commit -m "DOC: Build ${MANIFEST_FILE}"
git push -u origin master
popd

ssh-agent -k
echo "INFO: done"