name: Test Copycat

on:
  push:
    branches:
      - main
    paths:
      - "**/*.md"
      - "**/*.png"
      - ".github/workflows/main.yaml"

jobs:
  copycat:
    runs-on: ubuntu-latest
    steps:
      - name: Run copycat-action
        uses: andstor/copycat-action@v3
        with:
          personal_token: ${{ secrets.GH_TOKEN }}
          src_path: /
          dst_path: /
          dst_owner: parente
          dst_repo_name: sandbox
          src_branch: main
          dst_branch: copycat
          file_filter: "*.md,*.png"
          username: "${{ github.actor }}"
          email: ${{ github.actor }}@users.noreply.github.com
