name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Format metadata
        id: meta
        run: |
          echo "##[set-output name=date;]$(date "+%Y-%m-%d")"
          echo "##[set-output name=log;]$(git log --merges --format='%s: %b' origin/production..origin/master)"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: production-promotion
          title: Production release ${{ meta.outputs.date }}
          body: ${{ meta.outputs.log }}
