name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  promote-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
          fetch-depth: 0
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Format pull request details
        id: git_log
        run: |
          description=$(git log --merges --format='%s %b' origin/production..origin/master | cut -d ' ' -f4,7- | sed -e 's/^/* /')
          echo $description
          description="${description//'%'/'%25'}"
          echo $description
          description="${description//$'\n'/'%0A'}"
          echo $description
          description="${description//$'\r'/'%0D'}" 
          echo ${description}
          echo "::set-output name=date::$(date "+%Y-%m-%d")"
          echo "::set-output name=description::${description}"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: production-promotion
          title: Production release ${{ steps.git_log.outputs.date }}
          body: |
            ## Changes

            ${{ steps.git_log.outputs.description }}

            <!-- Autogenerated: Edits will lost on the next merge to master! -->
