name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  promote-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin master:master production:production
          git reset --hard master
      - name: Format pull request details
        id: git_log
        run: |
          log=$(git log --merges --format='%s %b' production..master | cut -d ' ' -f4,7- | sed -e 's/^/* /')
          echo $log
          log="${log//'%'/'%25'}"
          log="${log//$'\n'/'%0A'}"
          log="${log//$'\r'/'%0D'}" 
          echo "::set-output name=date::$(date "+%Y-%m-%d")"
          echo "::set-output name=log::${log}"
      - name: Create pull request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: production-promotion
          title: Production release ${{ steps.git_log.outputs.date }}
          body: |
            ## Changes

            ${{ steps.git_log.outputs.log }}

            <!-- Autogenerated: Edits will lost on the next merge to master! -->
