name: Create production promotion pull request
on:
  push:
    branches:
      - master
jobs:
  promote-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: production
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Compute git log
        id: git_log
        run: |
          echo "##[set-output name=date;]$(date "+%Y-%m-%d")"
          echo "##[set-output name=log;]$(git log --merges --format='%s %b' origin/production..origin/master | cut -d " " -f 4 -f7- | sed -e 's/^/* /')"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: production-promotion
          title: Production release ${{ steps.git_log.outputs.date }}
          body: |
            ## Changes

            ${{ steps.git_log.outputs.log }}

            <!-- Autogenerated: Edits will lost on the next merge to master! -->
